Repository Emulation-accurate/EmulationWebsite, pull requests merged in 2022-10, with the labels that each got.

#9 created the core team page
  core team.html
  images/aman jha.jpeg
  images/anurag chauhan.jpeg
  images/anurag verma.jpeg
  images/emulation logo.jpg
  images/nasir ali.jpeg
  images/satyam.jpeg
  images/shrey 2.jpeg
  images/shreyansh.jpeg
  style.css
Labels: good first issue, hactoberfest, hactoberfest2022

#11 create one readme for this project. #10
  README.md
  images/institute logo.png
Labels: hactoberfest-accepted

#13 logo size decreased
  style.css
Labels: hacktoberfest-accepted

#19 Certificate Generator
  Certificate-generator/certificate.js
  Certificate-generator/index.html
  Certificate-generator/logo/full_logo.png
  Certificate-generator/style.css
Labels: hacktoberfest-accepted

#15 Event page html only
  Event page
Labels: hacktoberfest2022, hacktoberfest-accepted

#21 Created Project Page
  Project Page/project.html
  Project Page/style.css
Labels: hacktoberfest-accepted

#36 Website: made event page better better with background color and design
  CSS/Event_Page.css
  Event page.html
Labels: hacktoberfest-accepted

#38 fix the issue of event page css file not loading
  Event page.html
Labels: hacktoberfest-accepted

#40 fix navbar not loading on project page
  CSS/project_page.css
  Event.html
  nav.html
  project.html
Labels: hacktoberfest-accepted

#44 upadted core team page
  CSS/CoreTeam.css
  core_team.html
  nav.html
Labels: hacktoberfest-accepted

#52 Added Footer
  core_team.html
Labels: hacktoberfest-accepted
